spring:
  mvc:
    static-path-pattern: /static/**
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost}:5432/user_db?currentSchema=auth
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated
    host: ${HOST_RABBIT:localhost}
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
    template:
      retry:
        enabled: false

amqp:
  queue:
    user-created: user-created.queue
  dlq:
    user-created-dlq: user-created.dlq

server:
  servlet:
    context-path: /api/v1
  port: 8080

jwt:
  private-key-path: ${JWT_KEYS_PATH:./keys/private_key.pem}/private_key.pem
  public-key-path: ${JWT_KEYS_PATH:./keys/public_key.pem}/public_key.pem
