version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ms-auth-infrastructure/src/main/resources/import.sql:/docker-entrypoint-initdb.d/import.sql
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    external: true
